# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Raghav
subtitle: SCIENCE!
description: >- # this means to ignore newlines until "baseurl:"
  Raghav Mallampalli's personal website.
author: Raghav Mallampalli
email: raghavmallampalli1234@gmail.com
avatar: assets/images/hair-and-specs-48.png

# IMPORTANT: You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/rghvmllmplli
facebook_url: 
googleplus_url:
instagram_url: https://www.instagram.com/raghavmallampalli/
linkedin_url: https://www.linkedin.com/in/raghav-mallampalli-a217a9174
github_url: https://github.com/raghavmallampalli
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

exclude: ["node_modules", ".history", "gulpfile.js", "package.json", "yarn.lock", "Gemfile.lock", "graphs_for_articles"]